name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Validate PHP syntax
      run: find . -name "*.php" -exec php -l {} \; || true

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku --version
        
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku auth:token
        heroku create heavens-above-${{ github.run_number }} || true
        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/heavens-above-${{ github.run_number }}.git
        git push heroku main