
name: Deploy to Heroku

on:
  push:
    branches: [ main, feature/deployment-setup ]
  pull_request:
    branches: [ main, feature/deployment-setup ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - name: Validate PHP syntax
      run: find . -name "*.php" -exec php -l {} \; || true

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "heavens-above-app-$(date +%s)"
        heroku_email: "muhammadsammad05@gmail.com"